---
# My first playbook 1
- hosts: ana
  become: yes

  vars_files:
  - ./roles/common/vars/vars_and_stuff.yml

  vars:
    ansible_become_pass: "{{ My_password }}"

  roles:
    - common
    - webserver

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)
...

