---
- name: My first playbook 1
  hosts: test

  remote_user: rdeseke
  become: yes
  vars:
    ansible_become_pass: "H1t0m120!"

  roles:
    - common

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)




...

