---
# My first playbook 3.5
- hosts: ana
  become: yes

  serial: 1  # allow the targets system to execute the tasks indiveduly

  vars_files:
  - ./roles/common/vars/vars_and_stuff.yml
  - ./roles/common/vars/open_vars.yml

  vars:
    ansible_become_pass: "{{ My_password }}"


  roles:
    - common
    - webserver

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)
...

