---
- name: My first playbook 1
  hosts: test
  become: yes
  become_user: root
  become_meathod: su
     --extra-vars='ansible_become_pass=H1t0m120!'



  roles:
    - common

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)
...

