---
# My first playbook 1
- hosts: test

- name: Super Richard
  become: yes
  vars:
    ansible_become_pass: "{{ My_password }}"

- name: Go to common role to run tasks.
  roles:
    - common

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)
...

