---
# My first playbook 1
- hosts: test

  vars_files:
  - ./roles/common/vars/vars_and_stuff.yml

  vars:
    ansible_become_pass: "{{ My_password }}"

- name: Super Richard
  become: yes



- name: Go to common role to run tasks.
  roles:
    - common

  tasks:
  - name: echo something
    shell: echo $(ip addr | grep inet)
...

