---
- name: Install our packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state absent
  with_items:
    - emacs

-import_tasks: ~/Ansible_Do/tasks/ricahrd_e.yml
...