# Common/tasks file
---
- name: Bring variable from vault
  include_vars:
    file: vars_and_stuff.yml
    name: My_password

- name: Install our packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ my_removes }}"

- import_tasks: ./roles/common/tasks/ricahrd_e.yml
...