---
- include_vars:
    file: vars_and_stuff.yml
    name: My_password


- name: Print vars_and_stuff.yml
  debug:
    var: My_password

  remote_user: rdeseke
  become: yes
  vars:
    ansible_become_pass: "{{ My_password }}"

- name: Install our packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ my_removes }}"

- import_tasks: ./roles/common/tasks/ricahrd_e.yml
...