---
- include_vars: vars_and_stuff.yml

  remote_user: rdeseke
  become: yes
  vars:
    ansible_become_pass: "vault_My_password"

- name: Install our packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ my_packages }}"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ my_removes }}"

- import_tasks: ./roles/common/tasks/ricahrd_e.yml
...