# webserver/tasks file
---

- debug:
    msg: "Docker password {{ Docker_password }} Password {{ My_password }}."

- name: install pip
  apt: name=python-pip state=present

# docker-py ?

- name: install docker package
  pip:  name=docker


- name: Add user in group 'docker'
  user:
    name: rdeseke
    groups: docker
    append: yes

#- name: Log into DockerHub
#  docker_login:
#    username: rdeseke
#    password: "{{ Docker_password }}"
#    reauthorize: yes
#    debug: yes





- name: Build docker image from Dockerfile
  docker_image:
    name: web
    path: /home/rdeseke/
    state: build

- name: Running the container
  docker_container:
    name: MyWebApp
    image: web:latest
    state: started

- name: Check if container is running
  shell: docker ps

...

